#!/usr/bin/perl

use strict;

&usage() unless scalar(@ARGV) == 3;

print "first item $ARGV[0]\n" ; 

my $taxoncode = $ARGV[0];
my $idField = $ARGV[1];
my $inputfile = $ARGV[2];
my $outputfile = "$taxoncode.fasta";

open(IN, $inputfile) || die "Can't open input file '$inputfile'\n";
open(OUT, "> $outputfile") || die "Can't open output file '$taxoncode.fasta'\n";

my %ids;
while(<IN>) {
  if (/\>/) {
    s/^\>\s*//;
    s/\s+/ /g;
    s/\s*\|\s*/\|/g;
    my @a = split(/[\s\|]/);
    my $id = $a[$idField-1];
    die "Fasta file '$inputfile' contains a duplicate id: $id\n" if $ids{$id};
    $ids{$id} = 1;
    print OUT ">$taxoncode|$id\n";

    
    
  } else {
    print OUT $_;
  }
}
close(OUT) ;

print "$outputfile produced\n" ; 


sub usage {
print STDERR "
Create an OrthoMCL compliant .fasta file, by adjusting definition lines.

Usage:
  orthomclAdjustFasta taxon_code id_field input_fasta_file

where:
  taxon_code:  a three or four letter unique abbreviation for the taxon
  id_field:    a number indicating what field in the definition line contains
               the protein ID.  Fields are separated by either ' ' or '|'. Any
               spaces immediately following the '>' are ignored.  The first
               field is 1. For example, in the following definition line, the
               ID (AP_000668.1) is in field 4:  >gi|89106888|ref|AP_000668.1|
  input_fasta_file:  the input fasta file
  output_fasta_file:  the output fasta file

Input file requirements:
  (1) .fasta format
  (2) a unique id is provided for each sequence, and is in the field specified
      by id_field

Output file format:
  (1) .fasta format
  (2) definition line is of the form:
         >taxoncode|unique_protein_id

";
exit(1);
}
